RUN_STRINGS = (
    "Detik berubah menit. Menit bertukar jam. Hari berganti minggu. Bahkan, bulan diganti tahun.Meski lintasan waktu kian usang, namun padamu aku tetap sayang.\n\n#aksara\n@RuangKerabat",
    "Kamu percaya soal ramalan? Kalaupun tidak, semoga kau percaya dengan mimpi yang diharapkan terjadi. Seperti keinginanku untuk menghabiskan seluruh waktuku bersama orang yang ada pada kata pertama pesan ini.\n\n#aksara\n@RuangKerabat",
    "Renjana memang ada.\nLebih nyata dari semesta.\nRenjana itu abadi.\nKekal melebihi dewa.\nRenjana itu dirimu.\nSeluruhnya renjanaku.\n\n#aksara\n@RuangKerabat",
    "Desiran rasa bahagia hangatkan tubuh, setelah pelukku bertemu pelukmu. Beginilah jika rindu tak dibatasi jarak. Bahkan dunia menganggap dirinya tak ada, hanya ada kita.\n\n#aksara\n@RuangKerabat",
    "Miliki dirimu seutuhnya, sebagian dariku sudah kau miliki.\nCintai dirimu sepenuhnya, separuh cintaku sudah milikmu.\nSeparuh aku, dirimu.\n\n#aksara\n@RuangKerabat",
    "Kamu...\nSebening embun di pagi hari\nIndah seperti pelangi di sore hari\nSejuk bagai udara pedesaan di malam hari\nKamu... Satu meski bukan Tuhan.\n\n#aksara\n@RuangKerabat",
    "Enak yah jadi kamu, kalau mau lihat keindahan, tinggal bercermin.\n\n#aksara\n@RuangKerabat",
    "Kusembunyikan luka ku, agar tak ada yang melihatnya\nKunikmati sendiri rasa sakitnya\nPerih, harus kuakui\nTapi aku tak mau lagi seperti dulu\nKuperlihatkan luka ku pada orang lain\nKemudian dibuatnya semakin berdarah.\n\n#aksara\n@RuangKerabat",
    "*Naruto run\nactivated*",
    "*Nezuko\nrun activated*",
    "Hey take\nresponsibilty for what you just did!",
    "May the odds\nbe ever in your favour.",
    "Run everyone, they\njust dropped a bomb 💣💣",
    "And they disappeared\nforever, never to be seen again.",
    "Legend has\nit, they're still running.",
    "Hasta la\nvista, baby.",
    "Ah, what a\nwaste. I liked that one.",
    "As The Doctor\nwould say... RUN!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MASHA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} memeluk {user2} dengan mesra di ruang tamu.",
    "{user1} mencium bibir {user2} dengan mesra di taman.",
    "{user1} mengajak {user2} ke biokop kemudian mereka berciuman.",
    "{user1} sedang bermesraan dengan {user2} di dalam mobil.",
    "{user1} memaksa {user2} untuk berciuman.",
    "{user2} diajak {user1} ke hotel untuk skididawdaw.",
    "{user2} diajak {user1} ke kost-nya untuk skididawdaw.",
    "{user1} mengajak {user2} kerumahnya kemudian skididawdaw.",
    "{user1} memaksa {user2} untuk vcs.",
    "{user1} sedang bermesraan dengan {user2} di kamarnya.",
    "{user1} memeluk {user2} dengan mesra di parkiran mall.",
    "{user1} memeluk {user2} dengan mesra di kamarnya.",
    "{user1} mencium bibir {user2} dengan mesra di parkiran mall.",
    "{user1} berciuman dengan {user2} di bioskop",
    "{user1} berciuman dengan {user2} di parkiran mall.",
    "{user1} berciuman dengan {user2} di kost-nya.",
    "{user1} berciuman dengan {user2} di dalam mobil",
    "{user2} dipaksa {user1} untuk berpelukan di pasar malam.",
    "{user2} dipaksa {user1} untuk berpelukan di parkiran mall.",
    "{user1} sedang asyik skididawdaw bersama {user2} di rumahnya.",
    "{user2} diajak {user1} ke rumahnya untuk skididawdaw.",
    "{user1} mengajak {user2} bercumbu di taman",
    "{user2} dan {user1} sedang bermesraan di tengah kerumunan orang demo.",
    "{user1} sedang berduaan dengan {user2} di dalam mobil dan mereka skididawdaw",
    "{user1} memeluk {user2} dengan mesra di dalam mobil.",
    "{user1} memaksa {user2} untuk skididawdaw di dalam mobil.",
    "{user1} mencium bibir {user2} dengan mesra di pasar malam.",
    "{user1} memeluk {user2} dengan mesra di pasar malam.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di parkiran mall.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di dapur.",
    "{user1} pergi ke rumah {user2} untuk skidawdaw.",
    "{user1} sedang berduaan dengan {user2} di kost-nya dan mereka skididawdaw.",
    "{user1} memeluk {user2} dengan mesra di dapur.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di hotel.",
    "{user1} mengajak {user2} liburan ke pantai untuk skididawdaw.",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!! 🏓🏓",
    "Saya disini!",
)

ITEMS = (
    "galon",
    "gitar listrik",
    "bambu runcing",
    "tongkat pramuka",
    "setrika panas",
    "kipas angin rusak",
    "TV tabung",
    "HP nokia jadul",
    "gerobak pasir",
    "pisau dapur",
    "buku paket sejarah",
    "sepatu brimob",
    "helm ojek",
    "ban mobil",
    "pipa besi",
    "kunci inggris",
    "raket nyamuk",
    "pentungan hansip",
    "kancut firaun",
    "stang motor Supra",
    "velg motor NMAX",
    "piring keramik",
    "batu gunung",
)

THROW = (
    "menggeplakkan",
    "menamparkan",
    "memukulkan",
    "melemparkan",
)

HIT = (
    "memukul",
    "menampol",
    "menampar",
    "menggeplak",
    "menghantam",
    "menampar",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("kepala", "ekor")

EIGHTBALL = [
    "Menahan napas selama 2 jam bisa membuatmu bertemu malaikat.",
    "Cobalah berjalan diatas kawat berduri yang dialiri listrik.",
    "Nampaknya kata *Bodoh* masih terlalu halus untuk mengejekmu.",
    "Tahukah kamu apa yang lebih kecil dari atom? Yaitu kemungkinanmu masuk surga.",
    "Maaf kalau aku mengatakan kamu bodoh, aku kira kamu sudah tau.",
    "Tenangkan dirimu dengan tarik napas dalam-dalam kemudian tahan hingga besok.",
    "Yang keluar dari mulutmu semuanya omong kosong, sama seperti isi kepalamu.",
    "Aku yakin IQ-mu tidak sebanyak usiamu.",
    "Tidurlah sambil memeluk harimau, itu bisa membuatmu jadi tidur selamanya.",
    "Maaf, perintah yang kamu masukkan tidak ada. Persis seperti isi kepalamu.",
    "Ada banyak orang yang mencarimu, pulanglah, mereka menunggumu di Rumah Sakit Jiwa.",
    "Apakah kau pernah mencoba membuat sesuatu yang lebih berguna dalam hidupmu? Kurasa tidak sekalipun.",
    "Kurasa setan tidak perlu merayu dan mengajakmu untuk berbuat dosa, malah mungkin kau dijadikan panutan.",
    "Satu-satunya kekuranganmu adalah, kau tidak punya kelebihan.",
    "Oh yeah!! Ternyata kau adalah wujud nyata kebodohan.",
    "*Ada Band* menciptakan lagu khusus untukmu, judulnya *Manusia Bodoh*.",
    "Permainan yang seru untukmu adalah ular tangga, tapi menggunakan ular sungguhan dan tanpa tangga.",
    "Kapan kau akan mulai berhenti untuk terus berbicara omong kosong?",
    "Sebenarnya kau tidak bodoh, hanya kurang beruntung dalam berfikir.",
    "Aku ragu berteman denganmu, kurasa kau dajjal yang sedang menyamar.",
]

DECIDE = ("Hilih bicit.", "Halah bacot.", "Bacot, ah.", "BACOT KAU.")

TABLE = (
    "🏃🏻‍♂️💨 🏃🏻‍♂️💨 🏃🏻‍♂️💨 KABUR!!!",
    "Lari! Ada orang gak jelas!",
    "Dahlah kabur aja…",
)
