RUN_STRINGS = (
    "Detik berubah menit. Menit bertukar jam. Hari berganti minggu. Bahkan, bulan diganti tahun.Meski lintasan waktu kian usang, namun padamu aku tetap sayang.\n\n#aksara\n@RuangKerabat",
    "Kamu percaya soal ramalan? Kalaupun tidak, semoga kau percaya dengan mimpi yang diharapkan terjadi. Seperti keinginanku untuk menghabiskan seluruh waktuku bersama orang yang ada pada kata pertama pesan ini.\n\n#aksara\n@RuangKerabat",
    "Renjana memang ada.\nLebih nyata dari semesta.\nRenjana itu abadi.\nKekal melebihi dewa.\nRenjana itu dirimu.\nSeluruhnya renjanaku.\n\n#aksara\n@RuangKerabat",
    "Desiran rasa bahagia hangatkan tubuh, setelah pelukku bertemu pelukmu. Beginilah jika rindu tak dibatasi jarak. Bahkan dunia menganggap dirinya tak ada, hanya ada kita.\n\n#aksara\n@RuangKerabat",
    "Miliki dirimu seutuhnya, sebagian dariku sudah kau miliki.\nCintai dirimu sepenuhnya, separuh cintaku sudah milikmu.\nSeparuh aku, dirimu.\n\n#aksara\n@RuangKerabat",
    "Kamu...\nSebening embun di pagi hari\nIndah seperti pelangi di sore hari\nSejuk bagai udara pedesaan di malam hari\nKamu... Satu meski bukan Tuhan.\n\n#aksara\n@RuangKerabat",
    "Enak yah jadi kamu, kalau mau lihat keindahan, tinggal bercermin.\n\n#aksara\n@RuangKerabat",
    "Kusembunyikan luka ku, agar tak ada yang melihatnya\nKunikmati sendiri rasa sakitnya\nPerih, harus kuakui\nTapi aku tak mau lagi seperti dulu\nKuperlihatkan luka ku pada orang lain\nKemudian dibuatnya semakin berdarah.\n\n#aksara\n@RuangKerabat",
    "Ada yang hilang selepas kau pergi\nTak ada lagi tempat merindu.\nBanyak penyesalan selepas kau pergi\nTak ada lagi cahaya.\nKini aku tersesat\nDi ujung pertemuan kita.\nTanpa tujuan dan tanpa harapan.\n\n#aksara\@RuangKerabat",
    "Tak perlu bingung memikirkannya, tapi…\nDiriku bukanlah diriku\nAku adalah aku, tapi…\nAku bukanlah aku\nAku adalah siapapun\nBisa saja aku adalah kamu, tapi…\nKamu bukanlah diriku\nDan diriku bukanlah aku, tapi…\nTak perlu bingung memikirkannya.\n\n#aksara\n@RuangKerabat",
    "Tak ada yang lebih menyenangkan dari rindu yang berujung temu.\n\n#aksara\n@RuangKerabat",
    "May the odds\nbe ever in your favour.",
    "Run everyone, they\njust dropped a bomb 💣💣",
    "And they disappeared\nforever, never to be seen again.",
    "Legend has\nit, they're still running.",
    "Hasta la\nvista, baby.",
    "Ah, what a\nwaste. I liked that one.",
    "As The Doctor\nwould say... RUN!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MASHA_TEMPLATES = (
    "GAUSA SLAP SLAP GUE! MAU LU GUE MUTE?.",
    "STOP SLAP GUE!",
    [
        "Lu gue mute dulu yah, mampus!",  # normal reply
        "Beruntung lu admin disini, jadi gue gabisa mute lu.",  # reply to admin
        "tmute",  # command
        "DIEM LU!",
        "DIAAAAMMM!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encr",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} memeluk {user2} dengan mesra di ruang tamu.",
    "{user1} mencium bibir {user2} dengan mesra di taman.",
    "{user1} mengajak {user2} ke biokop kemudian mereka berciuman.",
    "{user1} sedang bermesraan dengan {user2} di dalam mobil.",
    "{user1} memaksa {user2} untuk berciuman.",
    "{user2} diajak {user1} ke hotel untuk skididawdaw.",
    "{user2} diajak {user1} ke kost-nya untuk skididawdaw.",
    "{user1} mengajak {user2} kerumahnya kemudian skididawdaw.",
    "{user1} memaksa {user2} untuk vcs.",
    "{user1} sedang bermesraan dengan {user2} di kamarnya.",
    "{user1} memeluk {user2} dengan mesra di parkiran mall.",
    "{user1} memeluk {user2} dengan mesra di kamarnya.",
    "{user1} mencium bibir {user2} dengan mesra di parkiran mall.",
    "{user1} berciuman dengan {user2} di bioskop",
    "{user1} berciuman dengan {user2} di parkiran mall.",
    "{user1} berciuman dengan {user2} di kost-nya.",
    "{user1} berciuman dengan {user2} di dalam mobil",
    "{user2} dipaksa {user1} untuk berpelukan di pasar malam.",
    "{user2} dipaksa {user1} untuk berpelukan di parkiran mall.",
    "{user1} sedang asyik skididawdaw bersama {user2} di rumahnya.",
    "{user2} diajak {user1} ke rumahnya untuk skididawdaw.",
    "{user1} mengajak {user2} bercumbu di taman",
    "{user2} dan {user1} sedang bermesraan di tengah kerumunan orang demo.",
    "{user1} sedang berduaan dengan {user2} di dalam mobil dan mereka skididawdaw",
    "{user1} memeluk {user2} dengan mesra di dalam mobil.",
    "{user1} memaksa {user2} untuk skididawdaw di dalam mobil.",
    "{user1} mencium bibir {user2} dengan mesra di pasar malam.",
    "{user1} memeluk {user2} dengan mesra di pasar malam.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di parkiran mall.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di dapur.",
    "{user1} pergi ke rumah {user2} untuk skidawdaw.",
    "{user1} sedang berduaan dengan {user2} di kost-nya dan mereka skididawdaw.",
    "{user1} memeluk {user2} dengan mesra di dapur.",
    "{user2} dipaksa untuk skididawdaw dengan {user1} di hotel.",
    "{user1} mengajak {user2} liburan ke pantai untuk skididawdaw.",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!! 🏓🏓",
    "Saya disini!",
)

ITEMS = (
    "galon",
    "gitar listrik",
    "bambu runcing",
    "tongkat pramuka",
    "setrika panas",
    "kipas angin rusak",
    "TV tabung",
    "HP nokia jadul",
    "gerobak pasir",
    "pisau dapur",
    "buku paket sejarah",
    "sepatu brimob",
    "helm ojek",
    "ban mobil",
    "pipa besi",
    "kunci inggris",
    "raket nyamuk",
    "pentungan hansip",
    "kancut firaun",
    "stang motor Supra",
    "velg motor NMAX",
    "piring keramik",
    "batu gunung",
)

THROW = (
    "menggeplakkan",
    "menamparkan",
    "memukulkan",
    "melemparkan",
)

HIT = (
    "memukul",
    "menampol",
    "menampar",
    "menggeplak",
    "menghantam",
    "menampar",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("kepala", "ekor")

EIGHTBALL = [
    "Menahan napas selama 2 jam bisa membuatmu bertemu malaikat.",
    "Cobalah berjalan diatas kawat berduri yang dialiri listrik.",
    "Nampaknya kata *Bodoh* masih terlalu halus untuk mengejekmu.",
    "Tahukah kamu apa yang lebih kecil dari atom? Yaitu kemungkinanmu masuk surga.",
    "Maaf kalau aku mengatakan kamu bodoh, aku kira kamu sudah tau.",
    "Tenangkan dirimu dengan tarik napas dalam-dalam kemudian tahan hingga besok.",
    "Yang keluar dari mulutmu semuanya omong kosong, sama seperti isi kepalamu.",
    "Aku yakin IQ-mu tidak sebanyak usiamu.",
    "Tidurlah sambil memeluk harimau, itu bisa membuatmu jadi tidur selamanya.",
    "Maaf, perintah yang kamu masukkan tidak ada. Persis seperti isi kepalamu.",
    "Ada banyak orang yang mencarimu, pulanglah, mereka menunggumu di Rumah Sakit Jiwa.",
    "Apakah kau pernah mencoba membuat sesuatu yang lebih berguna dalam hidupmu? Kurasa tidak sekalipun.",
    "Kurasa setan tidak perlu merayu dan mengajakmu untuk berbuat dosa, malah mungkin kau dijadikan panutan.",
    "Satu-satunya kekuranganmu adalah, kau tidak punya kelebihan.",
    "Oh yeah!! Ternyata kau adalah wujud nyata kebodohan.",
    "*Ada Band* menciptakan lagu khusus untukmu, judulnya *Manusia Bodoh*.",
    "Permainan yang seru untukmu adalah ular tangga, tapi menggunakan ular sungguhan dan tanpa tangga.",
    "Kapan kau akan mulai berhenti untuk terus berbicara omong kosong?",
    "Sebenarnya kau tidak bodoh, hanya kurang beruntung dalam berfikir.",
    "Aku ragu berteman denganmu, kurasa kau dajjal yang sedang menyamar.",
]

DECIDE = ("Hilih bicit.", "Halah bacot.", "Bacot, ah.", "BACOT KAU.")

TABLE = (
    "🏃🏻‍♂️💨 🏃🏻‍♂️💨 🏃🏻‍♂️💨 KABUR!!!",
    "Lari! Ada orang gak jelas!",
    "Dahlah kabur aja…",
)